# Generated by Django 2.1.4 on 2019-04-04 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='subtitle',
            field=models.CharField(max_length=150, null=True, verbose_name='Sub Title'),
        ),
    ]
