# Generated by Django 2.1.4 on 2019-01-11 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190111_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_image',
            field=models.ImageField(blank=True, null=True, upload_to='blog_cover', verbose_name='Add Cover Photo'),
        ),
    ]
